---    
    - name: "copy nginx conf"
      template:
        src: templates/nginx.conf
        dest: "/etc/nginx/nginx.conf"
    - name: reload nginx service
      service:
        name: nginx
        state: reloaded